Main Project(WEBSITE)/dprojx/dappx/urls.py
# dappx/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    path('start/',views.newpre,name='newprescription'),
    url(r'^new/$', views.new, name='new'),
    path('record/', views.record, name='record'),
    path('mail/',views.sendmail,name='mail')
]

Main Project(WEBSITE)/dprojx/dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from dappx import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^dappx/', include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),

]

Main Project(WEBSITE)/dprojx/newpresciption/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^/$', views.newpre, name='newprescription'),
    url(r'^new/$', views.new, name='new'),
    url(r'^record/$', views.record, name='record'),
    ]

Main Project(WEBSITE)/dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .dappx import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^dappx/', include('dappx.urls')),
    url(r'^newprescription/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

Main Project(WEBSITE)/dprojx/dappx/models.py
# dappx/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
def __str__(self):
    return self.user.username

Gender_Choices=(
    ("Male","Male"),
    ("Female","Female"),
    ("Others","Others"),
)

class Menu(models.Model):
      Name  = models.CharField(max_length=100)
      Age = models.CharField(max_length=100)
      Gender = Gender_Choices

Main Project(WEBSITE)/dprojx/newpresciption/models.py
from django.db import models

# Create your models here.

Main Project(WEBSITE)/dprojx/dappx/forms.py
# dappx/forms.py
from django import forms
from dappx.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')


class MyForm(forms.Form):
    name = forms.CharField(label='Enter your name', max_length=100)
    email = forms.EmailField(label='Enter your email', max_length=100)
    feedback = forms.CharField(widget=forms.Textarea(attrs={'width':"100%", 'cols' : "80", 'rows': "20", }))

class NameForm(forms.Form):
    text = forms.CharField(label='Result', max_length=1000)

Main Project(WEBSITE)/dprojx/dappx/views.py
# dappx/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import MyForm,NameForm
from .NLP import nlp
from django.core.mail import send_mail,EmailMessage,EmailMultiAlternatives
from .emailsend import send
from dprojx.settings import EMAIL_HOST_USER
def index(request):
    return render(request,'index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login.html', {})


def responseform(request):
    form = MyForm()
    return render(request, 'responseform.html', {'form': form});
# Add prescription
def newpre(request):
    return render(request, 'newprescription.html', {})
def record(request):
    return render(request,'startrecord.html',{})
def new(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form = form.cleaned_data['text'],
            data = nlp(form)
            context ={
                'data': data
            }
            return render(request, 'record.html', context)

    # if a GET (or any other method) we'll create a blank form
    else:
        form = NameForm(request.POST)

    return render(request,'startrecord.html')

def sendmail(request):
    send()
    return render(request, 'sendmail.html', {})

Main Project(WEBSITE)/dprojx/newpresciption/views.py
from django.shortcuts import render
from dprojx.dappx.NLP import nlp

# Create your views here.
def newpre(request):
    return render(request, 'newprescription.html', {})
def new(request):
    data = nlp('patients name is saraj sharma  He is 25  years old and date of birth is 28th february 1999 he is suffering from acute bronchitis He is having symptoms which are dry cough for the last 3 days no fever and running nose he needs to take the following medicines  azithromycin 500 mg once a day for 3 days and robitussin 5 ml thrice a day for 5 days he is advised to drink warm water and he is not allowed to eat grapes')
    context ={
        'data' : data
    }
    return render(request,'record.html',context)
def record(request):
    return render()

Main Project(WEBSITE)/dprojx/dappx/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'dappx:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

Main Project(WEBSITE)/dprojx/dappx/templates/index.html
{% extends "dappx/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

Main Project(WEBSITE)/dprojx/dappx/templates/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

Main Project(WEBSITE)/dprojx/dappx/templates/registration.html
{% extends "dappx/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

Main Project(WEBSITE)/dprojx/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'%}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com"/font-awesome/4.5.0/css/font-awesome.min.css"/>
      <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!-- Mobile Metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- Site Metas -->
   <title>Life Care - Responsive HTML5 Multi Page Template</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- Site Icons -->
   <link rel="shortcut icon" href="{% static 'images/fevicon.ico.png' %}" type="image/x-icon" />
   <link rel="apple-touch-icon" href="{%static 'images/apple-touch-icon.png'%}">
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
   <!-- Site CSS -->
  <link rel="stylesheet" href="{%static 'css/login.css'%}">
   <link rel="stylesheet" href="{%static 'style.css'%}">
   <!-- Colors CSS -->
   <link rel="stylesheet" href="{%static 'css/colors.css'%}">
   <!-- ALL VERSION CSS -->
   <link rel="stylesheet" href="{%static 'css/versions.css'%}">
   <!-- Responsive CSS -->
   <link rel="stylesheet" href="{%static 'css/responsive.css'%}">
   <!-- Custom CSS -->
   <link rel="stylesheet" href="{%static 'css/custom.css'%}">
   <!-- Modernizer for Portfolio -->
   <script src="{%static 'js/modernizer.js' %}"></script>
   <!-- [if lt IE 9] -->
  </head>
{#  <div id="preloader">#}
{#         <img class="preloader" src="{%static 'images/loaders/heart-loading2.gif'%}" alt="">#}
{#      </div>#}
      <!-- END LOADER -->
      <body>
      <header>
         <div class="header-top wow fadeIn">
            <div class="container">
               <a class="navbar-brand" href="index.html"><img src="{% static 'images/logo.png' %}" alt="image"></a>
               <div class="right-header">
                  <div class="header-info">
                     <div class="info-inner">
                        <span class="icontop"><img src="{%static 'images/phone-icon.png'%}" alt="#"></span>
                        <span class="iconcont"><a href="tel:800 123 456">800 123 456</a></span>
                     </div>
                     <div class="info-inner">
                        <span class="icontop"><i class="fa fa-envelope" aria-hidden="true"></i></span>
                        <span class="iconcont"><a data-scroll href="mailto:info@yoursite.com">info@Lifecare.com</a></span>
                     </div>
                     <div class="info-inner">
                        <span class="icontop"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
                        <span class="iconcont"><a data-scroll href="#">Daily: 7:00am - 8:00pm</a></span>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="header-bottom wow fadeIn">
            <div class="container">
               <nav class="main-menu">
                  <div class="navbar-header">
                     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"><i class="fa fa-bars" aria-hidden="true"></i></button>
                  </div>

                  <div id="navbar" class="navbar-collapse collapse">
                     <ul class="nav navbar-nav">
                        <li><a data-scroll href="#home">Home</a></li>

                        <li><a class="navbar-link" href="http://127.0.0.1:8000/dappx/register/">Register</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="navbar-link" href="{% url 'dappx:record' %}"> New Prescription</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a href="http://127.0.0.1:8000/dappx/user_login/">Login</a></li>
          {% endif %}
                     </ul>
                  </div>
                </nav>
      </header>
          {% block body_block %}
      {% endblock %}
<footer id="footer" class="footer-area wow fadeIn">
         <div class="container">
            <div class="row">
               <div class="col-md-4">
                  <div class="logo padding">
                     <a href=""><img src="{%static 'images/logo.png'%}" alt=""></a>
                     <p>Locavore pork belly scen ester pine est chill wave microdosing pop uple itarian cliche artisan.</p>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="footer-info padding">
                     <h3>CONTACT US</h3>
                     <p><i class="fa fa-map-marker" aria-hidden="true"></i> PO Box 16122 Collins Street West Victoria 8007 Australia</p>
                     <p><i class="fa fa-paper-plane" aria-hidden="true"></i> info@gmail.com</p>
                     <p><i class="fa fa-phone" aria-hidden="true"></i> (+1) 800 123 456</p>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="subcriber-info">
                     <h3>SUBSCRIBE</h3>
                     <p>Get healthy news, tip and solutions to your problems from our experts.</p>
                     <div class="subcriber-box">
                        <form id="mc-form" class="mc-form">
                           <div class="newsletter-form">
                              <input type="email" autocomplete="off" id="mc-email" placeholder="Email address" class="form-control" name="EMAIL">
                              <button class="mc-submit" type="submit"><i class="fa fa-paper-plane"></i></button>
                              <div class="clearfix"></div>
                              <!-- mailchimp-alerts Start -->
                              <div class="mailchimp-alerts">
                                 <div class="mailchimp-submitting"></div>
                                 <!-- mailchimp-submitting end -->
                                 <div class="mailchimp-success"></div>
                                 <!-- mailchimp-success end -->
                                 <div class="mailchimp-error"></div>
                                 <!-- mailchimp-error end -->
                              </div>
                              <!-- mailchimp-alerts end -->
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <div class="copyright-area wow fadeIn">
         <div class="container">
            <div class="row">
               <div class="col-md-8">
                  <div class="footer-text">
                     <p>© 2018 Lifecare. All Rights Reserved.</p>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="social">
                     <ul class="social-links">
                        <li><a href=""><i class="fa fa-rss"></i></a></li>
                        <li><a href=""><i class="fa fa-facebook"></i></a></li>
                        <li><a href=""><i class="fa fa-twitter"></i></a></li>
                        <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                        <li><a href=""><i class="fa fa-youtube"></i></a></li>
                        <li><a href=""><i class="fa fa-pinterest"></i></a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end copyrights -->
      <a href="#home" data-scroll class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>
      <!-- all js files -->
      <script src="{%static 'js/all.js'%}"></script>
      <!-- all plugins -->
      <script src="{%static 'js/custom.js'%}"></script>
      <!-- map -->
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCNUPWkb4Cjd7Wxo-T4uoUldFjoiUA1fJc&callback=myMap"></script>
    </body>
</html>

Main Project(WEBSITE)/dprojx/templates/header.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'%}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com"/font-awesome/4.5.0/css/font-awesome.min.css"/>
      <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!-- Mobile Metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- Site Metas -->
   <title>Life Care - Responsive HTML5 Multi Page Template</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- Site Icons -->
   <link rel="shortcut icon" href="{% static 'images/fevicon.ico.png' %}" type="image/x-icon" />
   <link rel="apple-touch-icon" href="{%static 'images/apple-touch-icon.png'%}">
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
   <!-- Site CSS -->
  <link rel="stylesheet" href="{%static 'css/login.css'%}">
   <link rel="stylesheet" href="{%static 'style.css'%}">
   <!-- Colors CSS -->
   <link rel="stylesheet" href="{%static 'css/colors.css'%}">
   <!-- ALL VERSION CSS -->
   <link rel="stylesheet" href="{%static 'css/versions.css'%}">
   <!-- Responsive CSS -->
   <link rel="stylesheet" href="{%static 'css/responsive.css'%}">
   <!-- Custom CSS -->
   <link rel="stylesheet" href="{%static 'css/custom.css'%}">
   <!-- Modernizer for Portfolio -->
   <script src="{%static 'js/modernizer.js' %}"></script>
   <!-- [if lt IE 9] -->
  </head>
{#  <div id="preloader">#}
{#         <img class="preloader" src="{%static 'images/loaders/heart-loading2.gif'%}" alt="">#}
{#      </div>#}
      <!-- END LOADER -->
      <body>
      <header>
         <div class="header-top wow fadeIn">
            <div class="container">
               <a class="navbar-brand" href="index.html"><img src="{% static 'images/logo.png' %}" alt="image"></a>
               <div class="right-header">
                  <div class="header-info">
                     <div class="info-inner">
                        <span class="icontop"><img src="{%static 'images/phone-icon.png'%}" alt="#"></span>
                        <span class="iconcont"><a href="tel:800 123 456">800 123 456</a></span>
                     </div>
                     <div class="info-inner">
                        <span class="icontop"><i class="fa fa-envelope" aria-hidden="true"></i></span>
                        <span class="iconcont"><a data-scroll href="mailto:info@yoursite.com">info@Lifecare.com</a></span>
                     </div>
                     <div class="info-inner">
                        <span class="icontop"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
                        <span class="iconcont"><a data-scroll href="#">Daily: 7:00am - 8:00pm</a></span>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="header-bottom wow fadeIn">
            <div class="container">
               <nav class="main-menu">
                  <div class="navbar-header">
                     <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"><i class="fa fa-bars" aria-hidden="true"></i></button>
                  </div>

                  <div id="navbar" class="navbar-collapse collapse">
                     <ul class="nav navbar-nav">
                        <li><a data-scroll href="#home">Home</a></li>
            
                        <li><a class="navbar-link" href="http://127.0.0.1:8000/dappx/register/">Register</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="navbar-link" href="{% url 'dappx:newprescription' %}"> New Prescription</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a href="http://127.0.0.1:8000/dappx/user_login/">Login</a></li>
          {% endif %}
                     </ul>
                  </div>
                </nav>
      </header>
          {% block body_block %}
      {% endblock %}
      <footer id="footer" class="footer-area wow fadeIn">
         <div class="container">
            <div class="row">
               <div class="col-md-4">
                  <div class="logo padding">
                     <a href=""><img src="{%static 'images/logo.png'%}" alt=""></a>
                     <p>Locavore pork belly scen ester pine est chill wave microdosing pop uple itarian cliche artisan.</p>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="footer-info padding">
                     <h3>CONTACT US</h3>
                     <p><i class="fa fa-map-marker" aria-hidden="true"></i> PO Box 16122 Collins Street West Victoria 8007 Australia</p>
                     <p><i class="fa fa-paper-plane" aria-hidden="true"></i> info@gmail.com</p>
                     <p><i class="fa fa-phone" aria-hidden="true"></i> (+1) 800 123 456</p>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="subcriber-info">
                     <h3>SUBSCRIBE</h3>
                     <p>Get healthy news, tip and solutions to your problems from our experts.</p>
                     <div class="subcriber-box">
                        <form id="mc-form" class="mc-form">
                           <div class="newsletter-form">
                              <input type="email" autocomplete="off" id="mc-email" placeholder="Email address" class="form-control" name="EMAIL">
                              <button class="mc-submit" type="submit"><i class="fa fa-paper-plane"></i></button>
                              <div class="clearfix"></div>
                              <!-- mailchimp-alerts Start -->
                              <div class="mailchimp-alerts">
                                 <div class="mailchimp-submitting"></div>
                                 <!-- mailchimp-submitting end -->
                                 <div class="mailchimp-success"></div>
                                 <!-- mailchimp-success end -->
                                 <div class="mailchimp-error"></div>
                                 <!-- mailchimp-error end -->
                              </div>
                              <!-- mailchimp-alerts end -->
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <div class="copyright-area wow fadeIn">
         <div class="container">
            <div class="row">
               <div class="col-md-8">
                  <div class="footer-text">
                     <p>© 2018 Lifecare. All Rights Reserved.</p>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="social">
                     <ul class="social-links">
                        <li><a href=""><i class="fa fa-rss"></i></a></li>
                        <li><a href=""><i class="fa fa-facebook"></i></a></li>
                        <li><a href=""><i class="fa fa-twitter"></i></a></li>
                        <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                        <li><a href=""><i class="fa fa-youtube"></i></a></li>
                        <li><a href=""><i class="fa fa-pinterest"></i></a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end copyrights -->
      <a href="#home" data-scroll class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>
      <!-- all js files -->
      <script src="{%static 'js/all.js'%}"></script>
      <!-- all plugins -->
      <script src="{%static 'js/custom.js'%}"></script>
      <!-- map -->
     <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCNUPWkb4Cjd7Wxo-T4uoUldFjoiUA1fJc&callback=myMap"></script>
    </body>

Main Project(WEBSITE)/dprojx/templates/index.html
{% extends "header.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
  		  	{% include 'base.html' %}
  	<!--     <h1>Welcome to the Djungle !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %} -->
  </div>
</div>
{% endblock %}

Main Project(WEBSITE)/dprojx/templates/responseform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Forms Tutorial</title>
</head>
<body>
<h2>Django Forms Tutorial</h2>

<form>
    {% csrf_token %}
    {{form}}
<input type="submit" value="Submit" />
</form>
</body>
</html>

Main Project(WEBSITE)/dprojx/templates/sendmail.html
<!DOCTYPE html>
<html>
<head>
    <title>Success</title>
</head>
<body>
    <h1>email sent successfully!!!</h1>
</body>
</html>

Main Project(WEBSITE)/dprojx/templates/startrecord.html
{% extends 'base1.html' %}
{% load static %}
<script src="{% static 'app.js' %}"></script>
{% block body_block %}
    <br>
    <br><br><br><br><br><br><br><br>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
        <div>
            <div id='result'>
              Your text will appear here
            </div>
            <br>
            <div id= 'record'>
                <button onclick="startConverting()" class='btn btn-info btn-sm' id="re">record</button>
                <button onclick="stopRecording()" class='btn btn-info btn-sm' id="re">stop</button>
            </div>
            <form action="{% url 'dappx:new' %}" method="POST">
                {% csrf_token %}
                <label for="abc">Result:</label>
                <input id="abc" type="text" name="text" ><br>
                <input type="submit" value="Preview" >
            </form>
            <script src="{% static 'app.js' %}"></script>
            <script src="{% static 'my_jquery.js' %}"></script>
          </div>
{% endblock %}